version: '3.8'

services:
  app:
    container_name: smc_prod
    image: smc-prod:1.0.0
    build: .
    command: npm run start:prod
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always
  db:
    image: mongo
    volumes:
      - smc_data:/data/db
    networks:
      - backend
    restart: always
networks:
  backend:
volumes:
  smc_data:
